# Generated by Django 5.2 on 2025-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousolaboratorio',
            name='laboratorio',
            field=models.CharField(choices=[('G1', 'Laboratorio G1'), ('G2', 'Laboratorio G2'), ('G3', 'Laboratorio G3'), ('G4', 'Laboratorio G4'), ('G5', 'Laboratorio G5'), ('G6', 'Laboratorio G6'), ('K1', 'Laboratorio K1'), ('K2', 'Laboratorio K2'), ('H1', 'Laboratorio H1')], default='G1', max_length=50),
            preserve_default=False,
        ),
    ]
