# Generated by Django 5.2 on 2025-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registrousolaboratorio_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousolaboratorio',
            name='numero_estudiantes',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de estudiantes'),
        ),
    ]
