# Generated by Django 5.2 on 2025-04-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_registrousolaboratorio_numero_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carrera',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
