# Generated by Django 5.2 on 2025-04-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_docente_carrera_docente_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
